#!/bin/bash
# Syn_OS Security Environment Configuration
# Auto-generated by security automation

# Project root detection (security-safe)
if [[ -n "${BASH_SOURCE[0]}" ]]; then
    export PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
else
    export PROJECT_ROOT="$(pwd)"
fi

# Build directories (relative to project root)
export BUILD_DIR="${PROJECT_ROOT}/build"
export ISO_DIR="${BUILD_DIR}/iso"
export CACHE_DIR="${BUILD_DIR}/cache"
export LOGS_DIR="${BUILD_DIR}/logs"

# Security settings
export SECURITY_MODE="strict"
export PATH_VALIDATION="enabled"
export RELATIVE_PATHS_ONLY="true"

# Validate project root
if [[ ! -f "${PROJECT_ROOT}/Cargo.toml" ]]; then
    echo "❌ ERROR: Invalid project root detected: ${PROJECT_ROOT}"
    echo "🛡️ Security: Refusing to operate with invalid paths"
    exit 1
fi

echo "✅ Syn_OS environment configured securely"
echo "📁 Project Root: ${PROJECT_ROOT}"
echo "🔒 Security Mode: ${SECURITY_MODE}"
