groups:
  - name: security_alerts
    interval: 30s
    rules:
      # Unauthorized API access attempts
      - alert: UnauthorizedAPIAccess
        expr: |
          sum(rate(kong_http_status{status=~"401|403"}[5m])) by (service) > 10
        for: 2m
        labels:
          severity: warning
          category: security
        annotations:
          summary: "High rate of unauthorized access attempts"
          description: "Service {{ $labels.service }} is experiencing {{ $value }} unauthorized access attempts per second"

      # Vault seal status
      - alert: VaultSealed
        expr: vault_core_unsealed == 0
        for: 1m
        labels:
          severity: critical
          category: security
        annotations:
          summary: "Vault is sealed"
          description: "Vault has been sealed and requires unsealing"

      # API rate limit violations
      - alert: RateLimitViolations
        expr: |
          sum(rate(kong_ratelimiting_limiting_requests_total[5m])) by (service) > 50
        for: 5m
        labels:
          severity: warning
          category: security
        annotations:
          summary: "High rate of rate limit violations"
          description: "Service {{ $labels.service }} has {{ $value }} rate limit violations per second"

      # Suspicious traffic patterns
      - alert: SuspiciousTrafficPattern
        expr: |
          (
            sum(rate(kong_http_status{status="404"}[5m])) by (consumer) > 20
            and
            sum(rate(kong_http_status[5m])) by (consumer) > 100
          )
        for: 5m
        labels:
          severity: warning
          category: security
        annotations:
          summary: "Suspicious traffic pattern detected"
          description: "Consumer {{ $labels.consumer }} is generating suspicious traffic patterns"

      # Service communication outside allowed zones
      - alert: UnauthorizedZoneCommunication
        expr: |
          network_zone_violations_total > 0
        for: 1m
        labels:
          severity: critical
          category: security
        annotations:
          summary: "Unauthorized cross-zone communication detected"
          description: "Service {{ $labels.source_service }} attempted to communicate with {{ $labels.target_service }} across security zones"

      # Certificate expiration
      - alert: CertificateExpiringSoon
        expr: |
          (kong_certificate_expiry_timestamp - time()) / 86400 < 30
        for: 1h
        labels:
          severity: warning
          category: security
        annotations:
          summary: "SSL certificate expiring soon"
          description: "Certificate {{ $labels.sni }} will expire in {{ $value }} days"

      # Vault token expiration
      - alert: VaultTokenExpiringSoon
        expr: |
          (vault_token_ttl / 3600) < 24
        for: 30m
        labels:
          severity: warning
          category: security
        annotations:
          summary: "Vault token expiring soon"
          description: "Vault token for {{ $labels.service }} will expire in {{ $value }} hours"

      # Anomalous API usage
      - alert: AnomalousAPIUsage
        expr: |
          (
            abs(
              rate(kong_http_status[5m]) - 
              avg_over_time(rate(kong_http_status[5m])[1h:5m])
            ) > 
            3 * stddev_over_time(rate(kong_http_status[5m])[1h:5m])
          )
        for: 10m
        labels:
          severity: warning
          category: security
        annotations:
          summary: "Anomalous API usage detected"
          description: "Service {{ $labels.service }} is experiencing unusual API usage patterns"

      # Failed authentication spike
      - alert: AuthenticationFailureSpike
        expr: |
          rate(authentication_failures_total[5m]) > 10
        for: 2m
        labels:
          severity: critical
          category: security
        annotations:
          summary: "High rate of authentication failures"
          description: "{{ $value }} authentication failures per second detected"

      # Container privilege escalation
      - alert: ContainerPrivilegeEscalation
        expr: |
          container_privileged_status == 1
        for: 1m
        labels:
          severity: critical
          category: security
        annotations:
          summary: "Privileged container detected"
          description: "Container {{ $labels.container }} is running with privileged access"

      # Network segmentation violation
      - alert: NetworkSegmentationViolation
        expr: |
          network_policy_violations_total > 0
        for: 1m
        labels:
          severity: critical
          category: security
        annotations:
          summary: "Network segmentation policy violated"
          description: "{{ $value }} network policy violations detected from {{ $labels.source_pod }}"