[package]
name = "syn-kernel"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
# Core kernel dependencies
bootloader = { workspace = true }
volatile = { workspace = true }
spin = { workspace = true }
x86_64 = { workspace = true }
pic8259 = { workspace = true }
pc-keyboard = { workspace = true }
linked_list_allocator = { workspace = true }

# Error handling - simplified
anyhow = { workspace = true }

# Serialization - minimal
serde = { workspace = true, default-features = false, features = ["derive"] }

[features]
default = ["ai-integration"]
ai-integration = []
security-enhanced = []
debug-mode = []

[[bin]]
name = "kernel"
path = "src/main.rs"

[build-dependencies]
bootimage = "0.9"
