apiVersion: apps/v1
kind: Deployment
metadata:
  name: syn-os-core
  namespace: synos-core
  labels:
    app: syn-os-core
    component: kernel
    version: "1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syn-os-core
  template:
    metadata:
      labels:
        app: syn-os-core
        component: kernel
    spec:
      containers:
        - name: syn-os-kernel
          image: synos/kernel:latest
          ports:
            - containerPort: 8080
              name: api-port
            - containerPort: 8443
              name: secure-port
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: LOG_LEVEL
              value: "info"
            - name: SECURITY_MODE
              value: "strict"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
---
apiVersion: v1
kind: Service
metadata:
  name: syn-os-core-service
  namespace: synos-core
  labels:
    app: syn-os-core
spec:
  selector:
    app: syn-os-core
  ports:
    - port: 80
      targetPort: 8080
      name: api
    - port: 443
      targetPort: 8443
      name: secure
  type: ClusterIP
