[package]
name = "synos-ai-runtime"
version = "1.0.0"
edition = "2021"
description = "SynOS Native AI Runtime - Lightweight inference engine for no_std environments"
authors = ["SynOS Team"]
license = "MIT"

[lib]
path = "lib.rs"

[dependencies]
# Core no_std support
spin = "0.9"
lazy_static = { version = "1.4", features = ["spin_no_std"] }

# Cryptography for model encryption
aes-gcm = { workspace = true }
sha2 = { workspace = true }
getrandom = { workspace = true, features = ["custom"] }

[features]
default = []
std = []
tensorflow-lite = ["std"]  # TensorFlow Lite FFI requires std
onnx-runtime = ["std"]     # ONNX Runtime FFI requires std
pytorch = ["std"]          # PyTorch LibTorch FFI requires std
