[package]
name = "synos-security-orchestrator"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }

# For tool orchestration
reqwest = { version = "0.11", features = ["json"] }
regex = "1.10"

# For process execution
tokio-process = "0.2"
