
[package]
name = "synpkg"
version = "1.0.0"
edition = "2021"
authors = ["SynOS Team <dev@syn-os.org>"]
description = "SynOS Consciousness-Aware Package Manager"
license = "SynOS-1.0"
homepage = "https://syn-os.org"
repository = "https://github.com/syn-os/synpkg"
keywords = ["package-manager", "security", "consciousness", "ai"]
categories = ["command-line-utilities", "system-administration"]

[[bin]]
name = "synpkg"
path = "main.rs"

[lib]
name = "synpkg"
path = "lib.rs"

[dependencies]
# Core async runtime
tokio = { version = "1.0", features = ["full"] }

# Command-line interface
clap = { version = "4.0", features = ["derive"] }

# Error handling
anyhow = "1.0"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Date/time handling
chrono = { version = "0.4", features = ["serde"] }

# HTTP client
reqwest = { version = "0.11", features = ["json"] }

# Cryptography
ring = "0.17"

[dev-dependencies]
tokio-test = "0.4"
