[package]
name = "syn-security"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "syn_security"

[dependencies]
# Cryptography
ring = "0.17"
chacha20poly1305 = "0.10"
x25519-dalek = "2.0"
ed25519-dalek = "2.0"

# Error handling
anyhow = "1.0.75"
thiserror = "1.0.50"

# Serialization
serde = { version = "1.0", features = ["derive"] }

# Core utilities
spin = "0.9.8"

[features]
default = ["audit-logging", "threat-detection"]
audit-logging = []
threat-detection = []
zero-trust = []
