[package]
name = "synaptic-ai-engine"
version = "0.1.0"
edition = "2021"
description = "SynapticOS AI Engine - Core AI Runtime Infrastructure for Linux Distribution"
authors = ["SynOS Team"]
license = "MIT"

[dependencies]
# AI runtime dependencies
candle-core = { workspace = true }
candle-nn = { workspace = true }
ort = { workspace = true }  # ONNX Runtime
tch = { workspace = true }  # PyTorch

# System integration
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
log = { workspace = true }

# IPC and messaging
zeromq = { workspace = true }
nng = { workspace = true }

# Linux system integration
systemd = { workspace = true }
dbus = { workspace = true }
nix = { workspace = true }
libc = { workspace = true }

# Cryptography for secure model loading
ring = { workspace = true }
chacha20poly1305 = { workspace = true }

[features]
default = ["tensorflow-lite", "onnx", "pytorch"]
tensorflow-lite = []
onnx = ["ort"]
pytorch = ["tch"]
hardware-acceleration = []
linux-integration = ["systemd", "dbus"]
