#!/bin/bash
# Quick reference for what to use when

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║           SynOS Build Scripts - Quick Reference             ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "📍 Location: /home/diablorain/Syn_OS/scripts/02-build/core/"
echo ""
echo "🎯 WHAT TO USE:"
echo ""
echo "1. Building Complete SynOS ISO (PRODUCTION):"
echo "   → sudo ./ultimate-final-master-developer-v1.0-build.sh"
echo "   ⏱️  Time: 45-120 minutes"
echo "   📦 Output: Full bootable ISO with kernel + AI + security tools"
echo ""
echo "2. Quick Kernel Testing (DEVELOPMENT):"
echo "   → ./build-simple-kernel-iso.sh"
echo "   ⏱️  Time: 5 minutes"
echo "   📦 Output: Kernel-only ISO for testing"
echo ""
echo "3. Troubleshooting Environment:"
echo "   → ./verify-build-fixes.sh"
echo "   🔍 Checks: paths, components, mounts"
echo ""
echo "4. Manual Chroot Operations:"
echo "   → ./ensure-chroot-mounts.sh /path/to/chroot"
echo "   🔧 Mounts: /proc, /sys, /dev, /dev/pts"
echo ""
echo "5. Fix Locale Issues:"
echo "   → ./fix-chroot-locales.sh /path/to/chroot"
echo "   🔧 Sets: en_US.UTF-8"
echo ""
echo "❌ DON'T USE:"
echo "   • Anything in archived-legacy-scripts/"
echo "   • Those are for reference only"
echo ""
echo "📚 DOCUMENTATION:"
echo "   • README.md - Full guide"
echo "   • CONSOLIDATION_SUMMARY.md - What we did"
echo "   • SCRIPT_AUDIT_RESULTS.md - Technical details"
echo ""
echo "🆘 HELP:"
echo "   • Build failed? Just run the ultimate script again (it resumes)"
echo "   • Out of space? rm -rf build/workspace-*"
echo "   • Environment issues? Run verify-build-fixes.sh"
echo ""
echo "✨ TIP: Create an alias!"
echo "   echo 'alias synos-build=\"sudo $PWD/ultimate-final-master-developer-v1.0-build.sh\"' >> ~/.bashrc"
echo ""
