#!/bin/bash
# 🚨 CRITICAL: Pre-Codespace Git Repository Cleanup
# Large files MUST be removed before creating Codespace

echo "🚨 CRITICAL PRE-CODESPACE CLEANUP REQUIRED"
echo "=========================================="
echo ""
echo "⚠️  ISSUE: Git repository contains 14GB+ of large files that will:"
echo "   - Cause Codespace creation to fail or timeout"
echo "   - Consume excessive storage quota"
echo "   - Make git operations extremely slow"
echo ""
echo "🔍 LARGE FILES DETECTED:"
echo "   - synos-repo-backup.bundle (2.7GB)"
echo "   - Final_SynOS-1.0_ISO/ files (multiple 100MB+ files)"
echo "   - Burpsuite/Chrome binaries (400MB+)"
echo ""
echo "🔧 SOLUTION OPTIONS:"
echo ""
echo "OPTION 1: QUICK CLEAN (Recommended for immediate Codespace)"
echo "--------------------------------------------------------"
echo "1. Create a fresh repository for Codespace:"
echo "   git clone --depth 1 git@github.com:TLimoges33/Syn_OS-Dev-Team.git syn_os_clean"
echo "   cd syn_os_clean"
echo "   # Copy current development files (no large binaries)"
echo ""
echo "OPTION 2: COMPREHENSIVE CLEANUP (For permanent fix)"
echo "------------------------------------------------"
echo "1. Use git filter-repo to remove large files:"
echo "   git filter-repo --strip-blobs-bigger-than 10M"
echo "   git push --force-with-lease origin main"
echo ""
echo "OPTION 3: NEW CLEAN REPOSITORY (Fresh start)"
echo "--------------------------------------------"
echo "1. Create new repository with only source code"
echo "2. Preserve large files in separate storage/archive"
echo "3. Update remotes to point to clean repository"
echo ""
echo "🎯 RECOMMENDED IMMEDIATE ACTION:"
echo "Before creating Codespace, run Option 1 for a clean working environment."
echo ""
echo "⚡ QUICK COMMANDS:"
echo "cd /tmp"
echo "git clone --depth 1 git@github.com:TLimoges33/Syn_OS-Dev-Team.git syn_os_codespace"
echo "cd syn_os_codespace"
echo "# Then create Codespace from this clean repository"
echo ""
echo "🚀 After cleanup, repository will be <100MB instead of 14GB+"

# Check if git-filter-repo is available
if command -v git-filter-repo >/dev/null 2>&1; then
    echo ""
    echo "✅ git-filter-repo is available for comprehensive cleanup"
else
    echo ""
    echo "⚠️  git-filter-repo not installed. Install with:"
    echo "   pip3 install git-filter-repo"
fi
