apiVersion: v1
data:
  nats.conf: "\n                server_name: $POD_NAME\n                port: 4222\n\
    \                http_port: 8222\n                \n                jetstream\
    \ {\n                    max_memory_store: 2GB\n                    max_file_store:\
    \ 50GB\n                    store_dir: /data/jetstream\n                }\n  \
    \              \n                cluster {\n                    name: synaptic-cluster\n\
    \                    listen: 0.0.0.0:6222\n                    routes = [\n  \
    \                      nats://nats-0.nats:6222\n                        nats://nats-1.nats:6222\n\
    \                        nats://nats-2.nats:6222\n                    ]\n    \
    \            }\n                "
kind: ConfigMap
metadata:
  name: nats-config
  namespace: synaptic-os
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
  namespace: synaptic-os
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nats
  serviceName: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: nats:2.10-alpine
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
        name: nats
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 6222
          name: cluster
        - containerPort: 8222
          name: monitor
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 200m
            memory: 512Mi
        volumeMounts:
        - mountPath: /etc/nats
          name: config-volume
        - mountPath: /data/jetstream
          name: jetstream-storage
      volumes:
      - configMap:
          name: nats-config
        name: config-volume
  volumeClaimTemplates:
  - metadata:
      name: jetstream-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: fast-ssd
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: synaptic-os
spec:
  clusterIP: None
  ports:
  - name: client
    port: 4222
  - name: cluster
    port: 6222
  - name: monitor
    port: 8222
  selector:
    app: nats
---
