[package]
name = "synos-applications"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "synos_applications"
path = "mod.rs"

[dependencies]
# Core dependencies for no_std environment
spin = { workspace = true }

[features]
default = []
educational = []
ai_integration = []
