[package]
name = "syn-kernel"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

# Mark this package as not using the standard library
# This is critical for bare-metal development
[lib]
name = "syn_kernel"
path = "src/lib.rs"

[dependencies]
# Core kernel dependencies
bootloader = { workspace = true }
volatile = { workspace = true }
spin = { workspace = true }
x86_64 = { workspace = true }
pic8259 = { workspace = true }
pc-keyboard = { workspace = true }
linked_list_allocator = { workspace = true }
lazy_static = { version = "1.5", features = ["spin_no_std"] }

# Serde for AI interface (no_std compatible) - temporarily disabled due to conflicts
# serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }

# Additional dependencies for no_std environment
uart_16550 = "0.2"

# Error handling - using built-in core::result and core::error
# We don't need external error handling libraries for the kernel

[features]
default = ["ai-integration"]
ai-integration = []
security-enhanced = []
debug-mode = []

[[bin]]
name = "kernel"
path = "src/main.rs"

[build-dependencies]
bootimage = "0.10"

[package.metadata.bootimage]
test-args = [
    "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04",
    "-serial", "stdio",
    "-display", "none"
]
test-success-exit-code = 33
test-timeout = 300                  # (in seconds)
