{{- if .Values.security.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "syn-os.fullname" . }}-security
  namespace: {{ .Values.namespace | default "syn-os" }}-security
  labels:
    {{- include "syn-os.labels" . | nindent 4 }}
    component: security
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount.security | default 2 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "syn-os.selectorLabels" . | nindent 6 }}
      component: security
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "syn-os.selectorLabels" . | nindent 8 }}
        component: security
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "syn-os.serviceAccountName" . }}-security
      securityContext:
        {{- include "syn-os.securityContext" . | nindent 8 }}
      containers:
        - name: security-manager
          securityContext:
            {{- include "syn-os.containerSecurityContext" . | nindent 12 }}
          image: "{{ .Values.image.security.repository }}:{{ .Values.image.security.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: {{ .Values.service.security.port | default 8443 }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.service.security.metricsPort | default 9091 }}
              protocol: TCP
          env:
            - name: SYN_OS_SECURITY_MODE
              value: {{ .Values.security.mode | default "strict" | quote }}
            - name: SYN_OS_ZERO_TRUST_ENABLED
              value: {{ .Values.security.zeroTrust | default true | quote }}
            - name: SYN_OS_QUANTUM_CRYPTO_ENABLED
              value: {{ .Values.security.quantumCrypto | default true | quote }}
            - name: SYN_OS_THREAT_DETECTION_ENABLED
              value: {{ .Values.security.threatDetection | default true | quote }}
            {{- with .Values.security.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /security/health/live
              port: https
              scheme: HTTPS
            initialDelaySeconds: {{ .Values.security.livenessProbe.initialDelaySeconds | default 30 }}
            periodSeconds: {{ .Values.security.livenessProbe.periodSeconds | default 10 }}
          readinessProbe:
            httpGet:
              path: /security/health/ready
              port: https
              scheme: HTTPS
            initialDelaySeconds: {{ .Values.security.readinessProbe.initialDelaySeconds | default 5 }}
            periodSeconds: {{ .Values.security.readinessProbe.periodSeconds | default 5 }}
          resources:
            {{- if .Values.security.resources }}
            {{- toYaml .Values.security.resources | nindent 12 }}
            {{- else }}
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
            {{- end }}
          volumeMounts:
            - name: security-config
              mountPath: /etc/syn-os/security
              readOnly: true
            - name: tls-certs
              mountPath: /etc/ssl/certs/syn-os
              readOnly: true
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: security-config
          configMap:
            name: {{ include "syn-os.fullname" . }}-security-config
        - name: tls-certs
          secret:
            secretName: {{ include "syn-os.fullname" . }}-tls
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
