apiVersion: v1
kind: Service
metadata:
  name: {{ include "syn-os.fullname" . }}-core
  namespace: {{ .Values.namespace | default "syn-os" }}
  labels:
    {{- include "syn-os.labels" . | nindent 4 }}
    component: core
spec:
  type: {{ .Values.service.core.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.core.port | default 8080 }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.core.metricsPort | default 9090 }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "syn-os.selectorLabels" . | nindent 4 }}
    component: core
---
{{- if .Values.security.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "syn-os.fullname" . }}-security
  namespace: {{ .Values.namespace | default "syn-os" }}-security
  labels:
    {{- include "syn-os.labels" . | nindent 4 }}
    component: security
spec:
  type: {{ .Values.service.security.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.security.port | default 8443 }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.service.security.metricsPort | default 9091 }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "syn-os.selectorLabels" . | nindent 4 }}
    component: security
{{- end }}
