{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "syn-os.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default "syn-os" }}
  labels:
    {{- include "syn-os.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount | default false }}
---
{{- if .Values.security.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "syn-os.serviceAccountName" . }}-security
  namespace: {{ .Values.namespace | default "syn-os" }}-security
  labels:
    {{- include "syn-os.labels" . | nindent 4 }}
    component: security
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount | default false }}
{{- end }}
{{- end }}
