[package]
name = "synos-consciousness-daemon"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }

# Neural networks
# candle-core and candle-nn removed due to rand dependency conflicts
# Using pure Rust implementations instead
rand = { workspace = true }
ndarray = { workspace = true }

# IPC
nix = "0.27"
libc = "0.2"
