[build]
# Disable sanitizers for kernel development
rustflags = []

# Use stable toolchain features only for kernel
[target.'cfg(target_os = "none")']
rustflags = []

# Disable debug features that require runtime support
[env]
RUST_BACKTRACE = "0"

# Target-specific settings for x86_64 bare metal
[target.x86_64-unknown-none]
rustflags = [
    "-C", "target-feature=-mmx,-sse,+soft-float",
]
