apiVersion: apps/v1
kind: Deployment
metadata:
  labels: '{{- include "synapticos.labels" . | nindent 4 }}'
  name: '{{ include "synapticos.fullname" . }}-nats'
spec:
  replicas: '{{ .Values.replicaCount.nats }}'
  selector:
    matchLabels:
      app.kubernetes.io/component: nats
      app.kubernetes.io/instance: '{{ .Release.Name }}'
      app.kubernetes.io/name: '{{ include "synapticos.name" . }}'
  template:
    metadata:
      labels:
        app.kubernetes.io/component: nats
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/name: '{{ include "synapticos.name" . }}'
    spec:
      containers:
      - args:
        - --jetstream
        - --store_dir=/data
        - --http_port=8222
        image: nats:2.10.29-alpine
        name: nats
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 8222
          name: monitoring
        - containerPort: 6222
          name: routing
        resources: '{{ toYaml .Values.resources.nats | nindent 12 }}'
        volumeMounts:
        - mountPath: /data
          name: nats-storage
      volumes:
      - name: nats-storage
        persistentVolumeClaim:
          claimName: '{{ include "synapticos.fullname" . }}-nats-pvc'
