
# Quantum Algorithm Configuration
quantum_algorithms:
  neural_networks:
    max_qubits: 20
    max_layers: 10
    optimization_steps: 1000
    learning_rate: 0.1
    
  machine_learning:
    qsvm_kernel: "quantum"
    feature_map: "ZZFeatureMap"
    ansatz: "TwoLocal"
    shots: 1024
    
  optimization:
    vqe_optimizer: "COBYLA"
    qaoa_layers: 3
    max_iterations: 200
    convergence_threshold: 1e-6
    
  entanglement:
    bell_states: true
    ghz_states: true
    cluster_states: true
    purification_rounds: 5
