name: synos_companion
description: SynOS Mobile Companion App - Remote monitoring and management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # WebSocket communication
  web_socket_channel: ^2.4.0

  # State management
  provider: ^6.1.1

  # HTTP client
  http: ^1.1.2

  # Secure storage
  flutter_secure_storage: ^9.0.0

  # Push notifications
  firebase_messaging: ^14.7.6
  firebase_core: ^2.24.2

  # JSON serialization
  json_annotation: ^4.8.1

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/

  # Fonts
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
