_format_version: "3.0"
_transform: true

# Services Configuration
services:
  # n8n Workflow Service
  - name: n8n-service
    url: http://n8n:5678
    protocol: http
    host: n8n
    port: 5678
    path: /
    retries: 5
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    tags:
      - zone:critical
      - service:orchestration

  # Context Engine Service
  - name: context-engine-service
    url: http://context-engine:8080
    protocol: http
    host: context-engine
    port: 8080
    path: /api
    retries: 3
    connect_timeout: 30000
    write_timeout: 30000
    read_timeout: 30000
    tags:
      - zone:core
      - service:ai

  # JaceAI Email Service
  - name: jace-ai-service
    url: http://jace-ai:8081
    protocol: http
    host: jace-ai
    port: 8081
    path: /api
    retries: 3
    connect_timeout: 30000
    write_timeout: 30000
    read_timeout: 30000
    tags:
      - zone:app
      - service:communication

  # Speechify TTS Service
  - name: speechify-service
    url: http://speechify:8082
    protocol: http
    host: speechify
    port: 8082
    path: /api
    retries: 3
    connect_timeout: 30000
    write_timeout: 60000
    read_timeout: 60000
    tags:
      - zone:app
      - service:media

  # Vercel Connector Service
  - name: vercel-connector-service
    url: http://vercel-connector:8083
    protocol: http
    host: vercel-connector
    port: 8083
    path: /api
    retries: 2
    connect_timeout: 30000
    write_timeout: 30000
    read_timeout: 30000
    tags:
      - zone:dmz
      - service:deployment

# Routes Configuration
routes:
  # n8n Routes
  - name: n8n-webhook-route
    service: n8n-service
    protocols:
      - https
      - http
    methods:
      - GET
      - POST
      - PUT
      - DELETE
    paths:
      - /webhook
    strip_path: false
    preserve_host: true

  - name: n8n-api-route
    service: n8n-service
    protocols:
      - https
    methods:
      - GET
      - POST
      - PUT
      - DELETE
    paths:
      - /api/v1/workflows
    strip_path: false
    preserve_host: false

  # Context Engine Routes
  - name: context-engine-route
    service: context-engine-service
    protocols:
      - https
    methods:
      - GET
      - POST
    paths:
      - /api/v1/context
    strip_path: false

  # JaceAI Routes
  - name: jace-ai-route
    service: jace-ai-service
    protocols:
      - https
    methods:
      - POST
    paths:
      - /api/v1/email
    strip_path: false

  # Speechify Routes
  - name: speechify-route
    service: speechify-service
    protocols:
      - https
    methods:
      - POST
    paths:
      - /api/v1/tts
    strip_path: false

  # Vercel Routes
  - name: vercel-route
    service: vercel-connector-service
    protocols:
      - https
    methods:
      - GET
      - POST
    paths:
      - /api/v1/deploy
    strip_path: false

# Plugins Configuration
plugins:
  # Global Rate Limiting
  - name: rate-limiting
    config:
      minute: 100
      hour: 10000
      policy: local
      fault_tolerant: true
      hide_client_headers: false
      redis_ssl: false
      redis_ssl_verify: false

  # Global CORS
  - name: cors
    config:
      origins:
        - https://synapticos.local
        - https://localhost:3000
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        - X-Request-ID
      exposed_headers:
        - X-Auth-Token
        - X-Request-ID
      credentials: true
      max_age: 3600

  # Global Request Transformer
  - name: request-transformer
    config:
      add:
        headers:
          - X-Synapticos-Version:1.0
          - X-Request-ID:$(uuid)
      remove:
        headers:
          - Cookie
          - Set-Cookie

  # Global Response Transformer
  - name: response-transformer
    config:
      add:
        headers:
          - X-Synapticos-Response:true
          - Cache-Control:no-store
      remove:
        headers:
          - Server
          - X-Powered-By

  # IP Restriction for Admin Routes
  - name: ip-restriction
    route: n8n-api-route
    config:
      allow:
        - 172.20.1.0/24  # Zone 1 only
      status: 403
      message: Access denied

  # Bot Detection
  - name: bot-detection
    config:
      allow:
        - Googlebot
        - Bingbot
      deny:
        - curl
        - wget
        - python-requests

  # Request Size Limiting
  - name: request-size-limiting
    config:
      allowed_payload_size: 10
      size_unit: megabytes
      require_content_length: true

# Consumers (API Users)
consumers:
  - username: synapticos-internal
    custom_id: synapticos-001
    tags:
      - internal
      - privileged

  - username: external-api-user
    custom_id: external-001
    tags:
      - external
      - limited

# Authentication
keyauth_credentials:
  - consumer: synapticos-internal
    key: ${INTERNAL_API_KEY}
    tags:
      - internal

  - consumer: external-api-user
    key: ${EXTERNAL_API_KEY}
    tags:
      - external

# ACLs (Access Control Lists)
acls:
  - consumer: synapticos-internal
    group: admin
    tags:
      - admin-access

  - consumer: external-api-user
    group: user
    tags:
      - user-access

# Upstreams for Load Balancing
upstreams:
  - name: context-engine-upstream
    algorithm: round-robin
    slots: 10000
    healthchecks:
      active:
        healthy:
          interval: 10
          successes: 3
        unhealthy:
          interval: 5
          tcp_failures: 3
          timeouts: 3
          http_failures: 3
        http_path: /health
        timeout: 1
        type: http
      passive:
        healthy:
          successes: 5
        unhealthy:
          tcp_failures: 2
          timeouts: 2
          http_failures: 2
    tags:
      - critical-service

# Targets for Upstreams
targets:
  - upstream: context-engine-upstream
    target: context-engine:8080
    weight: 100
    tags:
      - primary

# Certificates
certificates:
  - cert: |
      -----BEGIN CERTIFICATE-----
      # Your SSL certificate here
      -----END CERTIFICATE-----
    key: |
      -----BEGIN PRIVATE KEY-----
      # Your private key here
      -----END PRIVATE KEY-----
    snis:
      - name: synapticos.local
    tags:
      - production

# SNIs
snis:
  - name: synapticos.local
    certificate: 
      id: # certificate ID will be auto-generated
    tags:
      - production