[package]
name = "dev-utils"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }

[[bin]]
name = "syn-dev"
path = "src/main.rs"
