[package]
name = "dev-utils"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
tokio = { version = "1.35", features = ["rt-multi-thread", "macros", "process", "fs"] }

[[bin]]
name = "syn-dev"
path = "src/main.rs"
