[package]
name = "common"
version = "4.3.0"
edition = "2021"
authors = ["Syn_OS Team"]
description = "Common utilities for Syn_OS"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
chrono = "0.4"

[dev-dependencies]
criterion = "0.4"
mockall = "0.11"
