[package]
name = "syn-security"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "syn_security"

[dependencies]
# Core dependencies
spin = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
chrono = { workspace = true }

# eBPF integration dependencies (optional for runtime)
libbpf-rs = { version = "0.21", optional = true }

# Cryptography (when std is available)
ring = { workspace = true, optional = true }
chacha20poly1305 = { workspace = true, optional = true } 
ed25519-dalek = { workspace = true, optional = true }

[features]
default = ["std", "audit-logging", "threat-detection", "ebpf-integration"]
std = ["ring", "chacha20poly1305", "ed25519-dalek", "libbpf-rs"]
audit-logging = []
threat-detection = []
quantum-security = []
ebpf-integration = ["libbpf-rs"]
