# Production Environment Configuration
environment: production
namespace: syn-os-prod

# High availability replica counts
replicaCount:
  core: 5
  security: 3

# Use stable production images
image:
  core:
    tag: "1.0.0"
  security:
    tag: "1.0.0"

# Production-optimized core configuration
core:
  logLevel: warn
  performanceMode: optimized
  resources:
    limits:
      cpu: 4000m
      memory: 8Gi
    requests:
      cpu: 2000m
      memory: 4Gi
  extraEnv:
    - name: SYN_OS_DEBUG_ENABLED
      value: "false"
    - name: SYN_OS_CACHE_SIZE
      value: "2048"
    - name: SYN_OS_PERFORMANCE_MODE
      value: "optimized"

# Maximum security configuration
security:
  mode: maximum
  level: enterprise
  auditLogging: true
  complianceMode: strict
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi

# Enable persistence with high-performance storage
persistence:
  enabled: true
  size: 100Gi
  storageClass: fast-ssd

# Aggressive autoscaling for production loads
autoscaling:
  enabled: true
  core:
    minReplicas: 3
    maxReplicas: 20
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 70
  security:
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 60

# Production-grade external dependencies
postgresql:
  enabled: true
  architecture: replication
  primary:
    resources:
      limits:
        cpu: 2000m
        memory: 4Gi
      requests:
        cpu: 1000m
        memory: 2Gi
  readReplicas:
    replicaCount: 2
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi

redis:
  enabled: true
  architecture: replication
  master:
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
  replica:
    replicaCount: 2
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi

nats:
  enabled: true
  cluster:
    enabled: true
    replicas: 3
  nats:
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
