
apiVersion: v1
kind: Namespace
metadata:
  name: synos-consciousness
  labels:
    consciousness.synos.io/enabled: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consciousness-operator
  namespace: synos-consciousness
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consciousness-operator
  template:
    metadata:
      labels:
        app: consciousness-operator
    spec:
      containers:
      - name: operator
        image: synos/consciousness-operator:latest
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: consciousness-api
  namespace: synos-consciousness
spec:
  selector:
    app: consciousness-operator
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
