apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consciousness-data-pvc
  namespace: synos-production
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: fast-ssd
