[system]
name = "SynOS"
version = "1.0.0-alpha"
build_type = "production"
consciousness_enabled = true
educational_mode = true

[boot]
timeout = 10
default_mode = "consciousness"
ai_optimization = true
graphics_mode = "auto"

[hardware]
auto_detect = true
ai_enhancement = true
learning_enabled = true

[consciousness]
level = "standard"
learning_rate = "adaptive"
optimization_enabled = true
