apiVersion: v1
kind: Service
metadata:
  labels: '{{- include "synapticos.labels" . | nindent 4 }}'
  name: '{{ include "synapticos.fullname" . }}-nats'
spec:
  ports:
  - name: client
    port: 4222
    protocol: TCP
    targetPort: client
  - name: monitoring
    port: 8222
    protocol: TCP
    targetPort: monitoring
  selector:
    app.kubernetes.io/component: nats
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/name: '{{ include "synapticos.name" . }}'
  type: '{{ .Values.service.type }}'
