# SynOS Cargo Audit Configuration
# Minimal working configuration for cargo-audit 0.21+

[advisories]
ignore = []

[database]
url = "https://github.com/RustSec/advisory-db"
fetch = true
stale = false

[output]
format = "terminal"
quiet = false

[yanked]
enabled = true
