[build]
# Conservative parallel builds to prevent system freeze
jobs = 2  # Two jobs for reasonable build speed without freezing
# Force all workspace members to use workspace target directory
target-dir = "target"
rustflags = [
    "-C", "target-cpu=haswell",    # Specifically target Haswell CPU (detected)
    "-C", "prefer-dynamic=no",     # Prefer static linking for performance
    "-W", "unsafe-code",           # Warn on unsafe code
]

# Workspace-wide features
[env]
# CARGO_INCREMENTAL disabled for sccache         # Enable incremental compilation
RUST_BACKTRACE = "1"           # Always enable backtraces for debugging

[profile.dev]
# Fast debug builds for development
debug = 1
overflow-checks = false
incremental = false  # Disabled for sccache
split-debuginfo = "unpacked"  # Faster linking on Linux
debug-assertions = false      # Disable debug assertions in dev for speed
panic = "abort"

[profile.release]
# Optimized release builds
opt-level = 3
lto = "fat"  # More aggressive LTO
codegen-units = 1
panic = "abort"
strip = true  # Strip symbols for smaller binaries

# Kernel-specific profile (security-hardened)
[profile.kernel]
inherits = "release"
opt-level = "s"  # Optimize for size in kernel
panic = "abort"
lto = "fat"
codegen-units = 1
debug = false
debug-assertions = false
overflow-checks = true  # Keep safety checks in kernel

# High-performance profile for critical components
[profile.performance]
inherits = "release"
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
debug = false
debug-assertions = false
overflow-checks = false

[alias]
# Development aliases
x = "run --release"
t = "test --all-targets"
c = "check --all-targets"
b = "build --release"
audit = "audit --deny warnings"
security = ["audit", "deny check"]
kernel-build = "build --manifest-path=src/kernel/Cargo.toml --target=x86_64-unknown-none --features=kernel-binary"
kernel-check = "check --manifest-path=src/kernel/Cargo.toml --target=x86_64-unknown-none --features=kernel-binary"
optimize = "build --release --target=x86_64-syn_os"
clean-deps = "tree --duplicates"
size-analysis = ["bloat", "--release", "--crates"]
profile-build = "build --release --timings"
minimal-versions = "check --features=minimal-versions"

[registries.crates-io]
protocol = "sparse"

[net]
retry = 2
git-fetch-with-cli = true
offline = false

[cargo-new]
vcs = "git"

[term]
color = "always"

# Kernel target configuration
[target.x86_64-unknown-none]
rustflags = [
    "-C", "target-cpu=haswell",      # Target specific CPU (Haswell supports AVX2)
    "-C", "target-feature=+crc32",   # Enable CRC32 instructions
    "-C", "target-feature=+popcnt",  # Enable POPCNT instruction
    "-C", "link-arg=--gc-sections",  # Remove unused sections
    "-C", "force-frame-pointers=yes", # Better debugging/profiling
]

# Security-hardened userspace target
[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "control-flow-guard",      # Control flow integrity
    "-C", "relocation-model=pic",    # Position independent code
]

# SynOS custom target
[target.x86_64-syn_os]
rustflags = [
    "-C", "target-cpu=haswell",
    "-C", "opt-level=s",
    "-C", "panic=abort",
    "-C", "link-arg=--gc-sections",
]

# Build std only for kernel targets
[target.x86_64-unknown-none.build-std]
features = "panic_immediate_abort"

[target.x86_64-unknown-none.build-std-features]
core = "panic_immediate_abort"
