created_timestamp: '2025-08-20T17:43:03.561916'
jetstream_subjects:
  ai_processing:
    description: AI model inference and learning requests
    max_age: 2h
    name: AI.PROCESSING.*
    retention: stream
  consciousness_events:
    description: Consciousness state changes and neural events
    max_age: 24h
    name: CONSCIOUSNESS.EVENTS.*
    retention: stream
  orchestrator_commands:
    description: Service orchestration commands
    max_age: 10m
    name: ORCHESTRATOR.COMMANDS.*
    retention: workqueue
  security_alerts:
    description: Security threat alerts and responses
    max_age: 7d
    name: SECURITY.ALERTS.*
    retention: stream
  system_monitoring:
    description: System health and performance metrics
    max_age: 1h
    name: SYSTEM.MONITORING.*
    retention: stream
server_config:
  cluster_mode: false
  jetstream_enabled: true
  monitoring_url: http://localhost:8222
  server_url: nats://localhost:4222
