[package]
name = "synos-ai-daemon"
version = "2.0.0"
edition = "2021"
authors = ["SynOS Development Team <dev@synos.ai>"]
description = "SynOS AI Consciousness Engine Daemon"

[[bin]]
name = "synos-ai-daemon"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }

# AI and ML libraries
candle = { workspace = true }
hf-hub = { workspace = true }
ndarray = { workspace = true }

# Neural Darwinism specific
rand = "0.8"
rayon = "1.10"

# System integration
nix = "0.29"
libc = "0.2"
systemstat = "0.2"

# Networking and communication
quinn = { workspace = true }
h3 = { workspace = true }
reqwest = { workspace = true }

# Configuration
config = "0.14"
toml = "0.8"