[package]
name = "syn-ai"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
# Core no_std dependencies
spin = { workspace = true }
lazy_static = { workspace = true }

# Serialization (no_std compatible)
serde = { workspace = true, default-features = false, features = ["derive"] }

[features]
default = ["local-inference", "decision-engine", "pattern-recognition"]
local-inference = []
decision-engine = []
pattern-recognition = []
