global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "consciousness-bridge"
    static_configs:
      - targets: ["consciousness-ai-bridge:8082"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "educational-platform"
    static_configs:
      - targets: ["educational-platform:8084"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "consciousness-dashboard"
    static_configs:
      - targets: ["consciousness-dashboard:8000"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "education-gui"
    static_configs:
      - targets: ["education-gui:8001"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "nats"
    static_configs:
      - targets: ["nats:8222"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]
    scrape_interval: 30s

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    scrape_interval: 30s
