# Syn_OS Master Configuration
# ============================

# System Information
system:
  name: "Syn_OS"
  version: "1.0.0-dev"
  codename: "Consciousness"
  build_date: "2025-09-02"
  base_os: "Syn_OS Native Kernel"

# Consciousness System Configuration
consciousness:
  enabled: true
  neural_darwinism:
    enabled: true
    evolution_interval: 1.0
    consciousness_threshold: 0.8
    populations:
      - id: "executive"
        size: 2000
        specialization: "executive"
      - id: "sensory"
        size: 1500
        specialization: "sensory"
      - id: "memory"
        size: 1000
        specialization: "memory"
      - id: "motor"
        size: 1000
        specialization: "motor"

  kernel_hooks:
    enabled: true
    device_path: "/dev/consciousness"
    shared_memory_size: 1048576 # 1MB
    ai_memory_pools:
      neural_weights: 268435456 # 256MB
      activation_maps: 134217728 # 128MB
      context_buffers: 67108864 # 64MB
      inference_cache: 536870912 # 512MB
      general: 268435456 # 256MB

# AI Integration Configuration
ai_integration:
  orchestration:
    enabled: true
    cost_budget_per_hour: 10.0
    max_concurrent_requests: 5

  claude:
    enabled: true
    api_key: "${CLAUDE_API_KEY}"
    base_url: "https://api.anthropic.com"
    model: "claude-3-sonnet-20240229"
    max_tokens: 4000
    temperature: 0.7
    rate_limit: 100

  gemini:
    enabled: false # Will be implemented
    api_key: "${GEMINI_API_KEY}"
    model: "gemini-pro"
    multimodal_model: "gemini-pro-vision"

  perplexity:
    enabled: false # Will be implemented
    api_key: "${PERPLEXITY_API_KEY}"
    model: "pplx-7b-online"

  local_llm:
    enabled: true
    lm_studio:
      api_endpoint: "http://localhost:1234/v1"
      model: "llama-2-7b-chat"
      max_tokens: 2048
      temperature: 0.7
      context_window: 4096

# Security Tool Orchestration
security_orchestration:
  enabled: true
  max_concurrent_scans: 3
  stealth_mode: false
  target_whitelist: [] # Empty means all targets allowed (be careful!)

  tools:
    nmap:
      enabled: true
      path: "/usr/bin/nmap"
      default_args: ["-sS", "-O", "-sV"]
      stealth_level: 0.8
      consciousness_compatibility: 0.9

    masscan:
      enabled: true
      path: "/usr/bin/masscan"
      default_args: ["--rate=1000"]
      requires_root: true
      stealth_level: 0.3
      consciousness_compatibility: 0.7

    nikto:
      enabled: true
      path: "/usr/bin/nikto"
      default_args: ["-Format", "json"]
      stealth_level: 0.6
      consciousness_compatibility: 0.8

    metasploit:
      enabled: true
      path: "/usr/bin/msfconsole"
      default_args: ["-q", "-x"]
      stealth_level: 0.7
      consciousness_compatibility: 0.95

    openvas:
      enabled: false # Requires separate setup
      path: "/usr/bin/gvm-cli"
      default_args: ["socket", "--xml"]
      stealth_level: 0.5
      consciousness_compatibility: 0.85

    wireshark:
      enabled: true
      path: "/usr/bin/tshark"
      default_args: ["-T", "json"]
      requires_root: true
      stealth_level: 0.9
      consciousness_compatibility: 0.8

# Database Configuration
database:
  postgresql:
    enabled: true
    host: "localhost"
    port: 5432
    database: "syn_os"
    username: "syn_os_user"
    password: "${POSTGRES_PASSWORD}"
    pool_size: 10
    max_overflow: 20

  redis:
    enabled: true
    host: "localhost"
    port: 6379
    password: "${REDIS_PASSWORD}"
    db: 0
    max_connections: 100

  vector_database:
    provider: "qdrant"
    host: "localhost"
    port: 6333
    collections:
      documents:
        vector_size: 1536
        distance: "Cosine"
      interactions:
        vector_size: 1536
        distance: "Dot"
      consciousness_states:
        vector_size: 768
        distance: "Cosine"

# Message Bus Configuration
message_bus:
  nats:
    enabled: true
    url: "nats://localhost:4222"
    username: "syn_os"
    password: "${NATS_PASSWORD}"
    jetstream:
      enabled: true
      store_dir: "/var/lib/nats"
      max_memory_store: "1GB"
      max_file_store: "10GB"

# Web Interface Configuration
web_interface:
  enabled: true
  host: "0.0.0.0"
  port: 8080
  debug: false
  cors_enabled: true
  cors_origins: ["http://localhost:3000", "https://syn-os.local"]

  dashboard:
    enabled: true
    port: 3000
    consciousness_visualization: true
    real_time_updates: true

  api:
    enabled: true
    rate_limiting: true
    rate_limit: "100/minute"
    authentication: true
    jwt_secret: "${JWT_SECRET}"
    jwt_expiration: 3600 # 1 hour

# Security Configuration
security:
  authentication:
    enabled: true
    method: "jwt"
    session_timeout: 3600
    max_failed_attempts: 5
    lockout_duration: 300

  encryption:
    at_rest: "AES-256-GCM"
    in_transit: "TLS 1.3"
    consciousness_data: "ChaCha20-Poly1305"

  audit_logging:
    enabled: true
    log_level: "INFO"
    log_file: "/var/log/syn_os/audit.log"
    max_file_size: "100MB"
    backup_count: 10

  firewall:
    enabled: true
    default_policy: "deny"
    allowed_ports: [22, 80, 443, 4222, 5432, 6333, 6379, 8080]

# Hardware Configuration
hardware:
  gpu_acceleration:
    enabled: false # Will be implemented in Phase 3
    cuda_enabled: false
    opencl_enabled: false

  tpm:
    enabled: false # Will be implemented in Phase 3
    version: "2.0"
    secure_boot: false

  cpu:
    consciousness_cores: 2
    max_threads: 8
    affinity_enabled: true

# Cloud Integration
cloud:
  enabled: false # Will be implemented in Phase 4
  providers: []
  sync_enabled: false
  backup_enabled: false

# Logging Configuration
logging:
  level: "INFO"
  format: "structured"
  output: "file"
  file: "/var/log/syn_os/syn_os.log"
  max_size: "100MB"
  backup_count: 5

  components:
    consciousness: "DEBUG"
    ai_integration: "INFO"
    security_orchestration: "INFO"
    kernel_hooks: "DEBUG"

# Performance Configuration
performance:
  monitoring:
    enabled: true
    interval: 5 # seconds
    metrics_retention: 86400 # 24 hours

  optimization:
    auto_scaling: false
    memory_optimization: true
    cpu_optimization: true
    consciousness_optimization: true

# Development Configuration
development:
  debug_mode: false
  hot_reload: false
  profiling: false
  test_mode: false
  mock_ai_responses: false

# Deployment Configuration
deployment:
  mode: "standalone" # standalone, distributed, cloud
  environment: "development" # development, staging, production

  iso_build:
    enabled: false
    output_dir: "/opt/syn_os/build/iso"
    compression: "xz"
    boot_mode: "uefi"
    secure_boot: false

  container:
    enabled: false
    base_image: "synos/native:latest"
    registry: "docker.io"
    tag: "syn-os:latest"

# Feature Flags
features:
  consciousness_visualization: true
  real_time_threat_hunting: false # Phase 5
  autonomous_exploitation: false # Phase 5
  cloud_collaboration: false # Phase 4
  hardware_acceleration: false # Phase 3
  quantum_cryptography: false # Future
  neural_interface: false # Future

# Experimental Features
experimental:
  enabled: false
  features: []

# Update Configuration
updates:
  auto_update: false
  check_interval: 86400 # 24 hours
  update_channel: "stable" # stable, beta, alpha
  backup_before_update: true

# Backup Configuration
backup:
  enabled: true
  interval: 3600 # 1 hour
  retention: 168 # 7 days
  consciousness_state: true
  configuration: true
  logs: false

  destinations:
    local:
      enabled: true
      path: "/var/backups/syn_os"
    cloud:
      enabled: false # Phase 4
