apiVersion: v1
kind: Namespace
metadata:
  name: syn-os
  labels:
    name: syn-os
    environment: base
    app.kubernetes.io/name: syn-os
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: syn-os-security
  labels:
    name: syn-os-security
    environment: base
    app.kubernetes.io/name: syn-os
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: security
---
apiVersion: v1
kind: Namespace
metadata:
  name: syn-os-monitoring
  labels:
    name: syn-os-monitoring
    environment: base
    app.kubernetes.io/name: syn-os
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: monitoring
