apiVersion: apps/v1
kind: Deployment
metadata:
  name: syn-os-security-manager
  namespace: syn-os-security
  labels:
    app: syn-os-security-manager
    component: security
    app.kubernetes.io/name: syn-os
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: security
spec:
  replicas: 2
  selector:
    matchLabels:
      app: syn-os-security-manager
  template:
    metadata:
      labels:
        app: syn-os-security-manager
        component: security
    spec:
      serviceAccountName: syn-os-security
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: security-manager
          image: syn-os/security:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
            - containerPort: 9091
              name: metrics
              protocol: TCP
          env:
            - name: SYN_OS_SECURITY_MODE
              value: "strict"
            - name: SYN_OS_ZERO_TRUST_ENABLED
              value: "true"
            - name: SYN_OS_QUANTUM_CRYPTO_ENABLED
              value: "true"
            - name: SYN_OS_THREAT_DETECTION_ENABLED
              value: "true"
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /security/health/live
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /security/health/ready
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: security-config
              mountPath: /etc/syn-os/security
              readOnly: true
            - name: tls-certs
              mountPath: /etc/ssl/certs/syn-os
              readOnly: true
      volumes:
        - name: security-config
          configMap:
            name: syn-os-security-config
        - name: tls-certs
          secret:
            secretName: syn-os-tls
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: syn-os-security
  namespace: syn-os-security
  labels:
    app.kubernetes.io/name: syn-os
    app.kubernetes.io/component: security
---
apiVersion: v1
kind: Service
metadata:
  name: syn-os-security-manager
  namespace: syn-os-security
  labels:
    app: syn-os-security-manager
    component: security
spec:
  type: ClusterIP
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: https
    - port: 9091
      targetPort: 9091
      protocol: TCP
      name: metrics
  selector:
    app: syn-os-security-manager
