[build]
target-dir = "target"

[target.x86_64-unknown-none]
runner = "bootimage runner"

[target.i686-unknown-none]
runner = "bootimage runner"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[alias]
ktest = "test --target x86_64-unknown-none"
krun = "run --target x86_64-unknown-none"
kbuild = "build --target x86_64-unknown-none"

[env]
RUST_BACKTRACE = "1"
