apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: syn-os-base
  annotations:
    description: "Base Kubernetes manifests for Syn_OS"

namespace: synos-core

resources:
  - namespace.yaml
  - core-deployment.yaml
  - security-deployment.yaml

commonLabels:
  project: syn-os
  environment: base
  managed-by: kustomize

images:
  - name: synos/kernel
    newTag: "1.0.0"
  - name: synos/security-manager
    newTag: "1.0.0"

configMapGenerator:
  - name: syn-os-config
    literals:
      - LOG_LEVEL=info
      - ENVIRONMENT=production
      - SECURITY_MODE=strict

secretGenerator:
  - name: syn-os-secrets
    literals:
      - api-key=placeholder-change-in-overlay
      - jwt-secret=placeholder-change-in-overlay

replicas:
  - name: syn-os-core
    count: 1
  - name: syn-os-security-manager
    count: 2

patches:
  - target:
      kind: Deployment
      name: syn-os-core
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "1Gi"
