apiVersion: apps/v1
kind: Deployment
metadata:
  name: syn-os-security-manager
  namespace: synos-security
  labels:
    app: syn-os-security
    component: security-manager
    version: "1.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: syn-os-security
  template:
    metadata:
      labels:
        app: syn-os-security
        component: security-manager
    spec:
      serviceAccountName: syn-os-security-sa
      containers:
        - name: security-manager
          image: synos/security-manager:latest
          ports:
            - containerPort: 8081
              name: security-port
          env:
            - name: SECURITY_LEVEL
              value: "maximum"
            - name: AUDIT_ENABLED
              value: "true"
            - name: THREAT_DETECTION
              value: "enabled"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: syn-os-security-service
  namespace: synos-security
  labels:
    app: syn-os-security
spec:
  selector:
    app: syn-os-security
  ports:
    - port: 8081
      targetPort: 8081
      name: security
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: syn-os-security-sa
  namespace: synos-security
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: syn-os-security-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: syn-os-security-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: syn-os-security-role
subjects:
  - kind: ServiceAccount
    name: syn-os-security-sa
    namespace: synos-security
