[package]
name = "synos-system-integration"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies for no_std environment
alloc = { version = "1.0", default-features = false, optional = true }

# Graphics and UI dependencies
embedded-graphics = { version = "0.8", default-features = false }
embedded-graphics-core = { version = "0.4", default-features = false }

# Logging and debugging
log = { version = "0.4", default-features = false }

# Serialization for configuration
serde = { version = "1.0", default-features = false, features = ["derive"] }

# Math and algorithms
libm = { version = "0.2", default-features = false }

# Memory management
linked_list_allocator = { version = "0.10", default-features = false }

# Time and timing
time = { version = "0.3", default-features = false }

# Error handling
anyhow = { version = "1.0", default-features = false }

# Collections
heapless = { version = "0.8", default-features = false }

# Random number generation
rand_core = { version = "0.6", default-features = false }

# Async support
futures-util = { version = "0.3", default-features = false }

# Hardware abstraction
nb = { version = "1.0", default-features = false }

# Networking (for system integration)
smoltcp = { version = "0.11", default-features = false, features = ["std", "medium-ethernet", "proto-ipv4", "proto-tcp", "socket-tcp"] }

# File system support
fatfs = { version = "0.4", default-features = false }

# Cryptography for security
aes = { version = "0.8", default-features = false }
sha2 = { version = "0.10", default-features = false }

# Compression
miniz_oxide = { version = "0.7", default-features = false }

# String processing
regex = { version = "1.0", default-features = false }

# Audio processing (for multimedia integration)
cpal = { version = "0.15", default-features = false, optional = true }

[features]
default = ["alloc", "graphics", "networking", "security", "educational"]

# Core features
alloc = ["dep:alloc"]
graphics = ["embedded-graphics", "embedded-graphics-core"]
networking = ["smoltcp"]
security = ["aes", "sha2"]
educational = []

# Advanced features
ai-consciousness = ["educational"]
multimedia = ["cpal"]
compression = ["miniz_oxide"]
filesystem = ["fatfs"]
async = ["futures-util"]

# Development features
debug = ["log"]
testing = []

[profile.dev]
panic = "abort"
opt-level = 0
debug = true
overflow-checks = true

[profile.release]
panic = "abort"
opt-level = "s"
debug = false
lto = true
codegen-units = 1
overflow-checks = false

[profile.test]
panic = "unwind"
opt-level = 1
debug = true
