apiVersion: apps/v1
kind: Deployment
metadata:
  name: syn-os-core
spec:
  template:
    spec:
      containers:
        - name: core
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
          env:
            - name: SYN_OS_LOG_LEVEL
              value: "debug"
            - name: SYN_OS_DEBUG_ENABLED
              value: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syn-os-security-manager
spec:
  template:
    spec:
      containers:
        - name: security-manager
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 125m
              memory: 256Mi
          env:
            - name: SYN_OS_SECURITY_MODE
              value: "development"
