apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: syn-os-development

namespace: syn-os-dev

resources:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development
  app.kubernetes.io/instance: syn-os-dev

patchesStrategicMerge:
  - deployment-patches.yaml

configMapGenerator:
  - name: syn-os-config
    behavior: merge
    literals:
      - SYN_OS_LOG_LEVEL=debug
      - SYN_OS_DEBUG_ENABLED=true
      - SYN_OS_METRICS_DETAILED=true
  - name: syn-os-security-config
    behavior: merge
    literals:
      - SECURITY_LEVEL=development
      - DEBUG_MODE=enabled

replicas:
  - name: syn-os-core
    count: 1
  - name: syn-os-security-manager
    count: 1

images:
  - name: syn-os/core
    newTag: "dev-latest"
  - name: syn-os/security
    newTag: "dev-latest"
