groups:
  - name: syn_os_consciousness_alerts
    rules:
      # Consciousness System Alerts
      - alert: ConsciousnessSystemDown
        expr: up{job="syn-os-consciousness"} == 0
        for: 30s
        labels:
          severity: critical
          service: consciousness
        annotations:
          summary: "Consciousness system is down"
          description: "Consciousness service {{ $labels.instance }} has been down for more than 30 seconds"

      - alert: ConsciousnessHighLatency
        expr: consciousness_decision_time_seconds > 0.1
        for: 2m
        labels:
          severity: warning
          service: consciousness
        annotations:
          summary: "High consciousness decision latency"
          description: "Consciousness decision time is {{ $value }}s on {{ $labels.instance }}"

      - alert: ConsciousnessLowAccuracy
        expr: consciousness_accuracy_score < 0.8
        for: 5m
        labels:
          severity: warning
          service: consciousness
        annotations:
          summary: "Low consciousness accuracy"
          description: "Consciousness accuracy score is {{ $value }} on {{ $labels.instance }}"

      - alert: NeuralDarwinismEvolutionStalled
        expr: increase(neural_darwinism_evolution_cycles[10m]) == 0
        for: 10m
        labels:
          severity: warning
          service: consciousness
        annotations:
          summary: "Neural Darwinism evolution stalled"
          description: "No evolution cycles in the last 10 minutes on {{ $labels.instance }}"

  - name: syn_os_security_alerts
    rules:
      # Security System Alerts
      - alert: SecurityDashboardDown
        expr: up{job="syn-os-security-dashboard"} == 0
        for: 30s
        labels:
          severity: critical
          service: security
        annotations:
          summary: "Security dashboard is down"
          description: "Security dashboard {{ $labels.instance }} has been down for more than 30 seconds"

      - alert: HighThreatLevelDetected
        expr: security_threat_level > 0.8
        for: 1m
        labels:
          severity: critical
          service: security
        annotations:
          summary: "High threat level detected"
          description: "Threat level {{ $value }} detected on {{ $labels.instance }}"

      - alert: SecurityDecisionBacklog
        expr: security_decision_queue_size > 100
        for: 2m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "Security decision backlog"
          description: "{{ $value }} security decisions queued on {{ $labels.instance }}"

      - alert: FailedAuthenticationSpike
        expr: increase(authentication_failures_total[5m]) > 50
        for: 1m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "Authentication failure spike"
          description: "{{ $value }} authentication failures in last 5 minutes on {{ $labels.instance }}"

  - name: syn_os_orchestrator_alerts
    rules:
      # Orchestrator System Alerts
      - alert: OrchestratorDown
        expr: up{job="syn-os-orchestrator"} == 0
        for: 30s
        labels:
          severity: critical
          service: orchestrator
        annotations:
          summary: "Orchestrator service is down"
          description: "Orchestrator {{ $labels.instance }} has been down for more than 30 seconds"

      - alert: OrchestratorHighMemoryUsage
        expr: process_resident_memory_bytes{job="syn-os-orchestrator"} / 1024 / 1024 / 1024 > 1
        for: 5m
        labels:
          severity: warning
          service: orchestrator
        annotations:
          summary: "Orchestrator high memory usage"
          description: "Orchestrator using {{ $value }}GB memory on {{ $labels.instance }}"

      - alert: OrchestratorHighCPUUsage
        expr: rate(process_cpu_seconds_total{job="syn-os-orchestrator"}[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: orchestrator
        annotations:
          summary: "Orchestrator high CPU usage"
          description: "Orchestrator CPU usage is {{ $value }}% on {{ $labels.instance }}"

  - name: syn_os_infrastructure_alerts
    rules:
      # Database Alerts
      - alert: PostgreSQLDown
        expr: up{job="postgres"} == 0
        for: 30s
        labels:
          severity: critical
          service: database
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database is down"

      - alert: PostgreSQLHighConnections
        expr: pg_stat_database_numbackends / pg_settings_max_connections * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: database
        annotations:
          summary: "PostgreSQL high connection usage"
          description: "PostgreSQL connection usage is {{ $value }}%"

      - alert: PostgreSQLReplicationLag
        expr: pg_replication_lag_seconds > 60
        for: 2m
        labels:
          severity: warning
          service: database
        annotations:
          summary: "PostgreSQL replication lag"
          description: "PostgreSQL replication lag is {{ $value }} seconds"

      # Redis Alerts
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 30s
        labels:
          severity: critical
          service: cache
        annotations:
          summary: "Redis is down"
          description: "Redis cache is down"

      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 90
        for: 5m
        labels:
          severity: warning
          service: cache
        annotations:
          summary: "Redis high memory usage"
          description: "Redis memory usage is {{ $value }}%"

      # NATS Alerts
      - alert: NATSDown
        expr: up{job="nats"} == 0
        for: 30s
        labels:
          severity: critical
          service: messaging
        annotations:
          summary: "NATS server is down"
          description: "NATS server {{ $labels.instance }} is down"

      - alert: NATSHighMessageRate
        expr: rate(nats_core_total_msgs[5m]) > 10000
        for: 5m
        labels:
          severity: warning
          service: messaging
        annotations:
          summary: "NATS high message rate"
          description: "NATS message rate is {{ $value }} msgs/sec on {{ $labels.instance }}"

  - name: syn_os_performance_alerts
    rules:
      # Performance Alerts
      - alert: HighResponseTime
        expr: http_request_duration_seconds{quantile="0.95"} > 1
        for: 5m
        labels:
          severity: warning
          service: performance
        annotations:
          summary: "High response time"
          description: "95th percentile response time is {{ $value }}s on {{ $labels.instance }}"

      - alert: LowThroughput
        expr: rate(http_requests_total[5m]) < 10
        for: 10m
        labels:
          severity: warning
          service: performance
        annotations:
          summary: "Low request throughput"
          description: "Request rate is {{ $value }} req/sec on {{ $labels.instance }}"

      - alert: ConsciousnessPerformanceDegradation
        expr: consciousness_decisions_per_second < 100
        for: 5m
        labels:
          severity: warning
          service: performance
        annotations:
          summary: "Consciousness performance degradation"
          description: "Consciousness decisions per second is {{ $value }} on {{ $labels.instance }}"

  - name: syn_os_business_alerts
    rules:
      # Business Logic Alerts
      - alert: AuthenticationPerformanceBelow9K
        expr: authentication_operations_per_second < 9000
        for: 5m
        labels:
          severity: warning
          service: authentication
        annotations:
          summary: "Authentication performance below A+ target"
          description: "Authentication ops/sec is {{ $value }}, below 9,798 target on {{ $labels.instance }}"

      - alert: SecurityGradeDropped
        expr: security_audit_score < 95
        for: 10m
        labels:
          severity: critical
          service: security
        annotations:
          summary: "Security grade dropped below A+"
          description: "Security audit score is {{ $value }}, below A+ threshold"

      - alert: ConsciousnessAdaptationFailure
        expr: increase(consciousness_adaptation_failures[1h]) > 5
        for: 30m
        labels:
          severity: warning
          service: consciousness
        annotations:
          summary: "Consciousness adaptation failures"
          description: "{{ $value }} adaptation failures in the last hour"