[package]
name = "dev-utils"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
<<<<<<< HEAD
tokio = { workspace = true, features = ["full"] }
=======
tokio = { workspace = true }
>>>>>>> production/develop

[[bin]]
name = "syn-dev"
path = "src/main.rs"
