[package]
name = "syn-libc"
version = "1.0.0"
edition = "2021"

[lib]
name = "synlibc"
crate-type = ["cdylib", "rlib"]

[dependencies]
# Memory allocator
linked_list_allocator = { version = "0.10", default-features = false, features = ["use_spin"] }
spin = { version = "0.9", default-features = false, features = ["mutex", "spin_mutex"] }
