apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: synapticos
    release: prometheus
  name: synapticos-monitor
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: synapticos
