
[bandit]
exclude_dirs = ["tests", "venv", "build"]
skips = ["B101"]  # Skip assert_used test

[bandit.any_other_function_with_shell_equals_true]
no_shell = [
    "subprocess.run",
    "subprocess.Popen",
    "subprocess.call"
]
