enterprise:
  # Enterprise MSSP Platform Configuration
  assessment_timeout: 1800 # 30 minutes
  max_concurrent_assessments: 10

  # Threat Intelligence Feeds
  threat_intel_feeds:
    - name: "AlienVault OTX"
      url: "https://otx.alienvault.com/api/v1/indicators/export"
      api_key_env: "OTX_API_KEY"
      refresh_interval: 3600
    - name: "ThreatCrowd"
      url: "https://api.threatcrowd.org/v2/"
      refresh_interval: 7200
    - name: "VirusTotal"
      url: "https://www.virustotal.com/vtapi/v2/"
      api_key_env: "VT_API_KEY"
      refresh_interval: 1800

  # Compliance Frameworks
  compliance_frameworks:
    - "SOC2"
    - "ISO27001"
    - "PCI-DSS"
    - "NIST"
    - "GDPR"
    - "HIPAA"
    - "FedRAMP"

  # Notification Channels
  notification_channels:
    - type: "email"
      config:
        smtp_server: "smtp.enterprise.com"
        port: 587
        username_env: "SMTP_USERNAME"
        password_env: "SMTP_PASSWORD"
        recipients:
          - "security-team@enterprise.com"
          - "ciso@enterprise.com"
    - type: "slack"
      config:
        webhook_url_env: "SLACK_WEBHOOK"
        channel: "#security-alerts"
    - type: "webhook"
      config:
        url: "https://enterprise.com/api/security/webhook"
        headers:
          Authorization: "Bearer ${WEBHOOK_TOKEN}"

  # Security Tool Categories
  tool_categories:
    devsecops:
      priority: 1
      tools: ["brakeman", "checkov", "vault", "conjur", "owasp_zap"]
    penetration_testing:
      priority: 2
      tools: ["nmap", "sqlmap", "metasploit", "burp_suite", "john_the_ripper"]
    threat_intelligence:
      priority: 3
      tools: ["alien_vault_otx", "osquery", "grr"]
    vulnerability_management:
      priority: 4
      tools: ["owasp_zap", "nmap", "sqlmap", "checkov", "brakeman"]
    incident_response:
      priority: 5
      tools: ["grr", "osquery", "wireshark", "volatility"]
    forensics:
      priority: 6
      tools: ["wireshark", "volatility", "osquery", "bulk_extractor"]

# Infrastructure Configuration
redis:
  host: "localhost"
  port: 6379
  db: 0
  password_env: "REDIS_PASSWORD"
  ssl: false

database:
  url: "postgresql://mssp:${DB_PASSWORD}@localhost:5432/enterprise_security"
  pool_size: 20
  max_overflow: 0
  echo: false

kubernetes:
  config_path: "~/.kube/config"
  namespace: "security-tools"

docker:
  registry: "registry.enterprise.com"
  base_images:
    security_tools: "registry.enterprise.com/security/tools:latest"
    forensics: "registry.enterprise.com/forensics/suite:latest"

# Security Assessment Profiles
assessment_profiles:
  rapid:
    timeout: 300 # 5 minutes
    tools: ["nmap", "owasp_zap"]
    severity_filter: ["critical", "high"]

  comprehensive:
    timeout: 3600 # 1 hour
    tools: ["nmap", "sqlmap", "owasp_zap", "checkov", "brakeman"]
    severity_filter: ["critical", "high", "medium"]

  compliance:
    timeout: 7200 # 2 hours
    tools: ["checkov", "owasp_zap", "brakeman", "vault", "conjur"]
    severity_filter: ["critical", "high", "medium", "low"]
    compliance_check: true

  penetration_test:
    timeout: 14400 # 4 hours
    tools:
      [
        "nmap",
        "sqlmap",
        "metasploit",
        "burp_suite",
        "john_the_ripper",
        "hashcat",
      ]
    severity_filter: ["critical", "high", "medium"]
    advanced_techniques: true

# Risk Scoring Configuration
risk_scoring:
  severity_weights:
    critical: 10.0
    high: 7.5
    medium: 5.0
    low: 2.5
    info: 1.0

  compliance_multipliers:
    SOC2: 1.5
    PCI_DSS: 2.0
    HIPAA: 1.8
    ISO27001: 1.3

  industry_adjustments:
    healthcare: 1.8
    financial: 2.0
    government: 1.9
    retail: 1.4
    technology: 1.2

# Incident Response Configuration
incident_response:
  severity_levels:
    critical:
      sla_minutes: 15
      escalation_levels: ["L1", "L2", "CISO", "CEO"]
      auto_actions: ["isolate", "collect_forensics", "notify_legal"]
    high:
      sla_minutes: 60
      escalation_levels: ["L1", "L2", "CISO"]
      auto_actions: ["isolate", "collect_forensics"]
    medium:
      sla_minutes: 240
      escalation_levels: ["L1", "L2"]
      auto_actions: ["monitor", "collect_logs"]
    low:
      sla_minutes: 1440
      escalation_levels: ["L1"]
      auto_actions: ["ticket"]

  automation_rules:
    malware_detection:
      triggers: ["malware", "virus", "trojan"]
      actions: ["quarantine", "forensics", "threat_hunt"]
    data_breach:
      triggers: ["exfiltration", "unauthorized_access", "data_loss"]
      actions: ["isolate", "legal_hold", "forensics", "notify_authorities"]
    ddos_attack:
      triggers: ["ddos", "dos", "flooding"]
      actions: ["rate_limit", "block_ips", "scale_infrastructure"]

# Monitoring and Alerting
monitoring:
  metrics_port: 8090
  health_check_interval: 30

  alerts:
    assessment_failure_threshold: 3
    high_risk_score_threshold: 80
    compliance_failure_threshold: 1
    tool_failure_threshold: 2

  dashboards:
    refresh_interval: 60
    retention_days: 90

# Enterprise Integrations
integrations:
  siem:
    type: "splunk"
    endpoint: "https://splunk.enterprise.com:8089"
    token_env: "SPLUNK_TOKEN"

  ticketing:
    type: "servicenow"
    endpoint: "https://enterprise.service-now.com"
    username_env: "SNOW_USERNAME"
    password_env: "SNOW_PASSWORD"

  vulnerability_scanner:
    type: "qualys"
    endpoint: "https://qualysapi.qualys.com"
    username_env: "QUALYS_USERNAME"
    password_env: "QUALYS_PASSWORD"

  threat_intelligence:
    type: "misp"
    endpoint: "https://misp.enterprise.com"
    api_key_env: "MISP_API_KEY"

# Security Tools Installation Paths
tool_paths:
  nmap: "/usr/bin/nmap"
  sqlmap: "/usr/bin/sqlmap"
  metasploit: "/usr/bin/msfconsole"
  burp_suite: "/opt/burpsuite/burpsuite"
  wireshark: "/usr/bin/tshark"
  john_the_ripper: "/usr/bin/john"
  hashcat: "/usr/bin/hashcat"
  aircrack_ng: "/usr/bin/aircrack-ng"
  brakeman: "/usr/local/bin/brakeman"
  checkov: "/usr/local/bin/checkov"
  owasp_zap: "/opt/zaproxy/zap-baseline.py"
  vault: "/usr/local/bin/vault"
  conjur: "/usr/local/bin/conjur"
  osquery: "/usr/bin/osqueryi"
  grr: "/opt/grr/grr_hunt.py"
  volatility: "/usr/bin/vol.py"
  bulk_extractor: "/usr/bin/bulk_extractor"

# Tool Dependencies
dependencies:
  system_packages:
    - "python3"
    - "python3-pip"
    - "ruby"
    - "java-11-openjdk"
    - "git"
    - "curl"
    - "wget"
    - "docker.io"
    - "postgresql-client"
    - "redis-tools"

  python_packages:
    - "asyncio"
    - "redis"
    - "psutil"
    - "requests"
    - "sqlalchemy"
    - "cryptography"
    - "docker"
    - "kubernetes"
    - "prometheus-client"
    - "pyyaml"
    - "psycopg2-binary"

  ruby_gems:
    - "brakeman"
    - "bundler"

  security_tools:
    - "nmap"
    - "sqlmap"
    - "metasploit-framework"
    - "wireshark"
    - "john"
    - "hashcat"
    - "aircrack-ng"
