[package]
name = "libtsynos"
version = "1.0.0"
edition = "2021"
description = "Userspace library for SynOS system calls"
authors = ["SynOS Team"]

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
libc = "0.2"

[dev-dependencies]
