[package]
name = "syn-kernel"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
# Core kernel dependencies
bootloader = { workspace = true }
volatile = { workspace = true }
spin = { workspace = true }
x86_64 = { workspace = true }
pic8259 = { workspace = true }
pc-keyboard = { workspace = true }
linked_list_allocator = { workspace = true }
lazy_static = { version = "1.5", features = ["spin_no_std"] }

# Serde for AI interface (no_std compatible)
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }

# Additional dependencies for no_std environment
uart_16550 = "0.2"

# Error handling - simplified
anyhow = { workspace = true }

[features]
default = ["ai-integration"]
ai-integration = []
security-enhanced = []
debug-mode = []

[[bin]]
name = "kernel"
path = "src/main.rs"

[build-dependencies]
bootimage = "0.9"
