[package]
name = "synshell"
version = "1.0.0"
edition = "2021"
authors = ["SynOS Development Team"]
description = "Security-focused command interpreter for SynOS"
license = "MIT"

[dependencies]
# Core dependencies for no_std environment
linked_list_allocator = "0.10"

# V1.9 Universal Command Integration
# Note: Universal command is std-based, shell is no_std
# Integration happens through the universal_command_bridge module (no external dependency needed)

[features]
default = []
std = []

# Profiles managed at workspace level - removed from package

[[bin]]
name = "synshell"
path = "main.rs"

[lib]
name = "synshell"
path = "lib.rs"
