name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -r requirements-consciousness.txt || true
      - name: Run security audit
        run: |
          python3 scripts/a_plus_security_audit.py || true
      - name: Run tests
        run: |
          make test || true
      - name: Lint Markdown
        run: |
          pip install markdownlint-cli || true
          markdownlint *.md || true
