[package]
name = "synos-llm-engine"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }

# HTTP server for API
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["cors"] }

# For LLM inference
reqwest = { version = "0.11", features = ["json"] }
